### ISSUE TITLE
wp profile for wp-admin

### ISSUE THREAD

**Issue by colemanedwards** [wp-cli/ideas#37] opened 2017-02-20 13:40 UTC
It would be very useful if wp profile analyzed php execution of wp-admin views since we often see slow performance from these pages

**Comment by danielbachhuber** [comment] 2017-02-20 15:20
Thanks for the suggestion, @colemanedwards !

This is a duplicate of https://github.com/wp-cli/profile-command/issues/18

**Closed by danielbachhuber** 2017-02-20 15:20 UTC

**Comment by colemanedwards** [comment] 2017-02-20 15:25
Ah! Great, thanks. I did look through profile-command/issues but didn't notice that one 😩. Makes sense!
