### ISSUE TITLE
Be able to set a plugin to be auto-updated or not to be auto-updated

### ISSUE THREAD

**Issue by lukecav** [wp-cli/ideas#148] opened 2020-07-30 14:02 UTC
Example commands;
```
wp plugin auto-update-enable woocommerce
wp plugin auto-update-disabled woocommerce
```

**Comment by mrwweb** [comment] 2021-02-13 23:01
Like this idea. Despite being first, it seems like this is a duplicate of #150 where there's been some discussion, so maybe close this one?

**Closed as completed** 2021-02-15 16:28 UTC
